<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>katalonTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c10f0c34-f54f-4fe5-b309-dd06882dae83</testSuiteGuid>
   <testCaseLink>
      <guid>af151108-9f50-4b3a-9317-1bc227998ae9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/addPost</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3e21965f-aaf0-49f7-9f68-43a81419b494</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/addPostNoMessage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cdbc1e3-eda4-47a9-8266-f5e671443905</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c5e14e2-0cef-4ac2-9316-acf6af8564fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/addSubForum</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05d46840-3f90-43f2-8b3c-b1b966b30b50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66e0e298-b403-466b-b7f9-cb0efd536756</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/addTopic</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f37e45b8-7cb0-434c-b053-abcac343f717</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fb20d79-8fec-4d44-a9b4-cc8f494b1bf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/advancedSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f7541ec-0aca-4b2d-80ce-35360864f1e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3761ad-3a3b-40d9-b70a-30e043ac7b5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3db6b379-e166-4a8b-a15e-a862a339f849</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/alreadyRegisteredUser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2b8b7727-7e16-4539-8a06-ba3e73cd0105</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/deletePost</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b5612a-b571-4552-bfc6-6aa9134226fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b6d8f60-74d6-4d8d-a418-79a3ed20abe5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/deleteTopic</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d14dc77c-c745-46d5-9e08-15522bf34635</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginNotRegistered</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>28ca0a58-9acb-4ebf-8869-7b9212fff0e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginRegisteredUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d33633-157d-4414-b89a-66cf6c5b26ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5dd6d5b5-3370-4af4-9520-47d3c44db3a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginWrongPassword</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>42cfa6b5-b58d-4a25-9f1f-06ab90fc9a80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/modifyProfile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>234f1eea-72ee-42ba-af8c-e9bc2bbba531</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>682c7fb1-20fe-4826-9fde-c144f82dd9ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegisterNewUser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f79dbe22-9d22-425d-9284-edcea4392391</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>325d2904-b094-488b-9a81-9d5b4a9c31ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b6d443-bfdf-438d-a0e7-7563a91ff77f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d4e1829-cb55-4eef-84e9-72ed63b02f56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
